name: Build-Dotnet

on: 
    push:
        branches:
            - main
    schedule:
        - cron: '30 6 * * 5' # every Friday 06:30 UTC

jobs:
    Build:
        runs-on: ubuntu-latest

        steps:
        - name: 'Checkout'
          uses: actions/checkout@v4

        - name: 'Setup dotnet'
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: '6.0.x'

        - name: 'Baixar dependencias'
          run: dotnet restore **/*.csproj

        - run: echo "Dependencias baixadas com sucesso!"

        - name: 'Compilar webapp'
          run: dotnet build **/*.csproj --no-restore
        
        - run: echo "Webapp gerado com sucesso!"